# Generated by Django 6.0.4 on 2026-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
