# Generated by Django 6.0.4 on 2026-05-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_college_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='short_name',
        ),
    ]
