# Generated by Django 6.0.4 on 2026-05-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_college_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(help_text='Short code for the university', max_length=20)),
                ('logo', models.URLField(blank=True, help_text='URL to university logo', max_length=500, null=True)),
                ('heroImage', models.URLField(blank=True, help_text='URL to university hero image', max_length=500, null=True)),
                ('title', models.CharField(help_text='Display title for the university', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name', max_length=255)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='App.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Stat value (e.g., '17,000+')", max_length=50)),
                ('label', models.CharField(help_text="Stat label (e.g., 'Students Served')", max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='App.university')),
            ],
        ),
    ]
