# Generated by Django 6.0.4 on 2026-05-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_admin_id_alter_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='heroImage',
            field=models.ImageField(blank=True, help_text='University hero image', null=True, upload_to='universities/hero/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, help_text='University logo image', null=True, upload_to='universities/logos/'),
        ),
    ]
