# Generated by Django 6.0.4 on 2026-05-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_universitystat_university_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
