# Generated by Django 6.0.4 on 2026-05-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
