# Generated by Django 6.0.6 on 2026-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('student', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=255)),
                ('courier_partner', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=255)),
                ('status', models.CharField(default='In Transit', max_length=50)),
                ('est_delivery', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
